DELETE http://localhost:3001/api/blogs/6544cae16b6c9913613970f9
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1bGVhYWwiLCJpZCI6IjY1MzU0Yjg3ZDc0YWQ5ZjM5NmIwYmVmMCIsImlhdCI6MTY5ODIyNzI2MX0.Yv8wlQ1YE7wFPNUePTRrj385yUJ6BI6DRcyeQS8wm4I
